#!/bin/bash
# gen_ghidra_shim.sh — generate saturn/experiments/daytona_byte_match/race_tu1/ghidra_shim.h
#
# Scans all *.ghidra.c files in the race_tu1 directory, collects the
# Ghidra placeholder types they reference plus any unresolved
# DAT_/PTR_/sub_/sym_ identifiers, and writes a shim header that makes
# the files parse under rcc.
#
# Re-run whenever new .ghidra.c files land. The shim is a throwaway
# artifact — we care about the diff between compiled .ghidra.c output
# and our refactored .c output, not the types themselves.
#
# Usage: bash saturn/tools/gen_ghidra_shim.sh

set -u
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO="$(cd "$SCRIPT_DIR/../.." && pwd)"
GHC="$REPO/saturn/experiments/daytona_byte_match/race_tu1"
OUT="$GHC/ghidra_shim.h"

if ! ls "$GHC"/*.ghidra.c > /dev/null 2>&1; then
    echo "No *.ghidra.c files in $GHC" >&2
    exit 1
fi

{
    cat <<'EOF'
/*
 * ghidra_shim.h — auto-generated by saturn/tools/gen_ghidra_shim.sh
 *
 * Minimal typedefs + extern declarations so the *.ghidra.c files
 * (raw Ghidra-decompiler output) parse under rcc. The shim doesn't
 * need to be semantically correct — it just has to satisfy the
 * parser. What matters is whether the .s output diverges from our
 * refactored (.c) version, which is measured by
 *     validate_byte_match.sh --ghidra
 *
 * DO NOT hand-edit. Re-run gen_ghidra_shim.sh to refresh.
 */

/* Ghidra placeholder types */
typedef unsigned char  byte;
typedef unsigned char  undefined1;
typedef unsigned short undefined2;
typedef unsigned long  undefined4;
typedef unsigned char  undefined;
typedef unsigned short ushort;
typedef unsigned int   uint;
typedef unsigned long  ulong;
typedef signed char    sbyte;

/* "code" is Ghidra's function-type placeholder. Used as
 *   (*(code *)ptr)()
 * so it has to be a callable type. `int()` works — gives rcc a
 * function signature to cast through. */
typedef int code();

/* extern declarations for DAT_/PTR_/sub_/sym_ symbols the decompiled
 * bodies reference. Types are opaque on purpose — we only need them
 * to parse, not to match production types. */
EOF

    # Collect all matching identifiers, sorted & deduped.
    # Ghidra data-symbol prefixes we've seen in race_tu1:
    #   DAT_*/dat_*  — data, integer or pointer per use site
    #   PTR_*         — typed pointer (decompiler-inferred)
    #   sym_*         — unresolved symbol address
    #   sub_*         — subroutine
    #   puRam_*/pcRam_*  — RAM-typed variable (Ghidra auto-name)
    grep -hoE "\b(DAT_[0-9a-fA-F]+|dat_[0-9a-fA-F]+|PTR_[A-Z]+_[0-9a-fA-F]+|sym_[0-9a-fA-F]+|sub_[0-9a-fA-F]+|puRam[0-9a-fA-F]+|pcRam[0-9a-fA-F]+|psRam[0-9a-fA-F]+)\b" \
        "$GHC"/*.ghidra.c | sort -u | while read -r sym; do
        case "$sym" in
            PTR_*)
                # PTR_FUN_*/PTR_SUB_* — used as `(*(code *)PTR)()`.
                # Declaring as `code` (function type) means a plain
                # `PTR_X()` also parses, and `(code *)PTR_X` casts cleanly.
                printf 'extern code %s;\n' "$sym"
                ;;
            sub_*)
                # subroutines called directly
                printf 'extern int %s();\n' "$sym"
                ;;
            puRam*|pcRam*|psRam*)
                # RAM-typed variables — opaque pointer
                printf 'extern char *%s;\n' "$sym"
                ;;
            *)
                # DAT_/dat_/sym_ — declared as int so both direct int
                # assignments and pointer casts parse cleanly.
                printf 'extern int %s;\n' "$sym"
                ;;
        esac
    done

    # Cross-function calls between .ghidra.c files. Ghidra emits both
    # mixed-case and lower-case variants of the same function name.
    # Collect the set of *defined* functions so we can skip shimming
    # those (they'd collide with the actual definitions).
    defined_fns="$(grep -hE "^[a-zA-Z_][a-zA-Z0-9_ *]*FUN_[0-9a-fA-F]+\s*\(" \
        "$GHC"/*.ghidra.c | grep -oE "FUN_[0-9a-fA-F]+" | sort -u)"
    echo ""
    echo "/* cross-function callees (FUN_* identifiers used but not defined) */"
    grep -hoE "\bFUN_[0-9a-fA-F]+\b" "$GHC"/*.ghidra.c | sort -u | while read -r fn; do
        # Skip if this function is defined in one of the .ghidra.c files.
        if echo "$defined_fns" | grep -q "^${fn}$"; then
            continue
        fi
        printf 'extern int %s();\n' "$fn"
    done
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines)"
