#!/usr/bin/env python3
"""Read function names from stdin, emit a noregsave pragma block."""
import sys

names = [line.strip() for line in sys.stdin if line.strip()]

print("/* SHC v5.0 §3.10 noregsave tags — auto-derived from Ghidra")
print(" * unaff_* annotations across the TU. Empirical batch from the")
print(" * pragma workstream Phase D probe; will be regenerated by")
print(" * derive_pragmas.py. If a specific function regresses under")
print(" * noregsave it should be excluded here with a brief note. */")
for fn in names:
    print(f"#pragma noregsave({fn})")
