#!/usr/bin/env python3
"""One-shot bootstrap: generate the TU .c file + TODO tracker.

Walks every function in a production TU .s file (in prod order),
pulls in the Ghidra C reference for each, and wraps it in `#if 0`
with a "TODO: sanitize" marker. Already-sanitized functions (passed
via the --sanitized flag with a path to an existing .c) get inlined
verbatim and checked off.

Running this more than once is not safe — it overwrites the TU
file and TODO.md. Use it to bootstrap, then hand-edit from there.
"""
import argparse, os, re, sys

def main():
    p = argparse.ArgumentParser()
    p.add_argument("--tu-path", required=True,
                   help="prod TU .s path, e.g. /mnt/.../FUN_06044060.s")
    p.add_argument("--ghidra-dir", required=True,
                   help="dir with Ghidra .c references")
    p.add_argument("--out-dir", required=True,
                   help="where to create the TU .c and TODO")
    p.add_argument("--tu-name", required=True,
                   help="TU base name, e.g. FUN_06044060")
    p.add_argument("--sanitized", action="append", default=[],
                   help="fn=path/to/sanitized.c — inlined + checked off")
    args = p.parse_args()

    sanitized_map = {}
    for s in args.sanitized:
        fn, path = s.split("=", 1)
        with open(path) as f:
            sanitized_map[fn] = f.read()

    with open(args.tu_path) as f:
        tu_text = f.read()
    funcs = [m.group(1) for m in
             re.finditer(r'^(FUN_[0-9a-fA-F]+):', tu_text, re.MULTILINE)]

    os.makedirs(args.out_dir, exist_ok=True)

    # ---- TU .c file ----
    tu_c = os.path.join(args.out_dir, f"{args.tu_name}.c")
    with open(tu_c, "w") as f:
        f.write(f"""/*
 * {args.tu_name}.c — Daytona CCE race-module TU master file.
 *
 * Prod reference: {os.path.basename(args.tu_path)}
 * Generated by saturn/tools/generate_tu_scaffold.py. Do not rerun —
 * hand-editing is the workflow. Each function starts in a "TODO:
 * sanitize" #if 0 block containing its raw Ghidra decompilation;
 * sanitizing means unwrapping the block, fixing type issues (Gap 0
 * style), and adding pragmas as needed so the TU compiles cleanly.
 *
 * The end goal (methodology milestone): every function in this TU
 * compiles via rcc AND matches prod byte-for-byte at tier-1, such
 * that the assembled .o drops into the DaytonaCCE retail build
 * producing a byte-identical ROM.
 *
 * Progress tracked in TODO.md.
 */

#include "ghidra_shim.h"

/* ──────────────────────────────────────────────────────────────
 * Shared declarations (DATs, globals, intra-TU prototypes).
 * Populated as functions are sanitized and common references
 * surface. Each entry notes which function(s) reference it.
 * ────────────────────────────────────────────────────────────── */

""")

        for i, fn in enumerate(funcs):
            order = f"{i+1:03d}/{len(funcs):03d}"
            sep = "═" * 20
            f.write(f"\n/* {sep} [{order}] {fn} {sep} */\n\n")
            ghidra_c = os.path.join(args.ghidra_dir, f"{fn}.c")
            if fn in sanitized_map:
                f.write(f"/* SANITIZED. See TODO.md. */\n")
                f.write(sanitized_map[fn])
                if not sanitized_map[fn].endswith("\n"):
                    f.write("\n")
            elif os.path.exists(ghidra_c):
                with open(ghidra_c) as gf:
                    raw = gf.read()
                f.write(f"/* TODO: sanitize — raw Ghidra decomp below. */\n")
                f.write("#if 0\n")
                f.write(raw)
                if not raw.endswith("\n"):
                    f.write("\n")
                f.write("#endif\n")
            else:
                f.write(f"/* TODO: no Ghidra C reference available. "
                        f"Function body unknown — author from prod .s. */\n")

    print(f"Wrote {tu_c}")

    # ---- TODO tracker ----
    todo = os.path.join(args.out_dir, "TODO.md")
    with open(todo, "w") as f:
        f.write(f"# {args.tu_name} TU sanitization progress\n\n")
        f.write(f"Goal: all {len(funcs)} functions compile cleanly as part "
                f"of `{args.tu_name}.c`. Sanitization = fix Ghidra type "
                f"issues, add pragmas as needed. Byte-match is a later "
                f"phase — for now, compile-clean is the bar.\n\n")
        f.write(f"## Status\n\n")
        f.write(f"- Sanitized: {len(sanitized_map)} / {len(funcs)}\n")
        f.write(f"- Remaining: {len(funcs) - len(sanitized_map)}\n\n")
        f.write(f"## Checklist\n\n")
        f.write(f"Prod-order. Check off when the function's `#if 0` block "
                f"is unwrapped AND the TU compiles cleanly.\n\n")
        for i, fn in enumerate(funcs):
            mark = "x" if fn in sanitized_map else " "
            suffix = ""
            if fn in sanitized_map:
                suffix = " — **byte-identical** (see `byte_match_baselines/`)"
            elif not os.path.exists(
                    os.path.join(args.ghidra_dir, f"{fn}.c")):
                suffix = " — ⚠ no Ghidra reference"
            f.write(f"- [{mark}] {i+1:03d}. `{fn}`{suffix}\n")

    print(f"Wrote {todo}")

if __name__ == "__main__":
    main()
